### ISSUE TITLE
11 healer configuration

### ISSUE THREAD

**Issue by rainecheck** [rossnichols/ABP-Naxx#3]
Hey, occasionally we have to run 11 healers on 4H, and our preferred solution is to have only 2 healers at Zeliek, meaning that healers leave Zeliek at 2 marks rather than 3. Is there any easy way to configure this in the addon? Or would having configuration solutions for <12 healers be a possible new feature?

**Comment by rossnichols** [comment]
Hm, interesting concept. There's no way to configure that right now. Do you think this is a one-off for 11 healers or would we need special logic for e.g. 10 healers too? Would other guilds want to remove the healer on other bosses or is Zeliek a safe bet?

**Comment by rainecheck** [comment]
I wouldn't be surprised if a 10 healer config removed another slot from the top, so from Blammo. Luckily we haven't been in such a position. It could also be generified to say, allow for 13 healer comps with 4 healer slots on Thane for guilds who are having trouble with Thane meteor damage. I imagine right now those groups would be having two healers move on one of the marks, but some might opt to have healers stay for a 4th - uncertain.

**Comment by rossnichols** [comment]
The main issue with this idea is that it means your overall mark rotation is a multiple of 11 (or 10), not 12... the addon assumes that everyone has the same rotation multiple today. All the rotations are also hardcoded, which makes making rotation updates like this pretty challenging if there was any amount of variability in it at all (e.g., which healer spot to drop).

**Comment by rossnichols** [comment]
I played around with it and 10 is the min you can go, at 9 the rotation is too fast and you can't drop all your stacks. I can see about adding an option for 11 healers that has 2 at Zeliek and calling it a day.

**Comment by rossnichols** [comment]
Sorry, at this point in Classic I don't feel this feature meets the bar anymore - the risk of regression is too great, and I no longer raid Naxx myself.
